- README.md
- README 프로젝트 구조 오류 수정 및 프로젝트 소개 작성
> 📝 Docs: README 프로젝트 구조 오류 수정 및 프로젝트 소개 작성

- README.md
> Revert "📝 Docs: README 프로젝트 구조 오류 수정 및 프로젝트 소개 작성"

- EatPic-iOS/Resources/Colors.xcassets/GrayColor/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray010.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray020.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray030.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray040.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray050.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray060.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray070.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray080.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray090.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/MainColor/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/MainColor/green010.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/MainColor/green020.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/MainColor/green030.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/MainColor/green040.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/MainColor/green050.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/MainColor/green060.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/SubColor/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/SubColor/pink050.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/SubColor/pink060.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/SubColor/pink070.colorset/Contents.json
- EatPic-iOS/Sources/Screens/ContentView.swift
- EatPic-iOS/Sources/Utilites/Extensions/Color+Extensions.swift
- EatPic-iOS/Sources/Utilites/Extensions/Font+Extensions.swift
- 피그마 디자인 시스템에 기반한 폰트 및 색상 설정
close #8 
> 🎉 [Chore] 디자인 시스템 설정

- EatPic-iOS/Sources/Components/PrimaryButton.swift
- 앱 내 메인 버튼 공통 컴포넌트 제작 완료
- 버튼의 배경색, 텍스트 색상과 폰트, 버튼의 높이, 모서리의 둥근 정도, 버튼 실행 클로저 파라미터 지원
- 프로필 원형 이미지 공통 컴포넌트 구현
closes #17 
> ✨ [Feat] PrimaryButton 컴포넌트 제작

- EatPic-iOS/Sources/Components/PicCardView.swift
(기존 한글로 작성했던 브랜치명을 영어로 변경 후 삭제했더니 pr이 자동으로 close 되어 다시 pr 올립니더...!)
PicCardView 컴포넌트를 제작하였습니다.
- 카드 뒷면 (ReceiptDetailCardView) 제작
- 가운데 사각형(이미지 부분) 크기는 분명 가로세로 동일한데 왜 오른쪽만 흰색으로 남는지 잘 모르겠습니더.. 설마 sf symbol의 문제는 아니겠지요..?
- 이렇게 작성하면 컴포넌트로 사용하는 데에 문제 없는지 냉철한. 확인 부탁드립니다 ㅎㅎ
closes #13 
> ✨ [Feat] PicCardView 컴포넌트 제작

- EatPic-iOS/Sources/Components/ReactionBarView.swift
사용자가 콘텐츠(PicCard 등)에 대해 하나의 이모지 리액션을 선택할 수 있도록 구성된 리액션 바 컴포넌트입니다.
https://github.com/user-attachments/assets/ea631356-4ad9-49a8-94b5-354e9e28dd0e
- ReactionItemView
- @Binding을 써서 관리하도록 만들었는데,, 이렇게 구성해도 되는건지, 안된다면 어떻게 수정해야하는지 확인부탁드립니더,,
closes #27 
> ✨ [Feat] ReactionBarView 컴포넌트 제작

- EatPic-iOS/Sources/Components/PicCardView.swift
- EatPic-iOS/Sources/Components/ReactionBarView.swift
- EatPic-iOS/Sources/Components/ReciptDetailCardView.swift
폰트 수정 전 작업했던 뷰의 폰트를 수정하였습니다
- ReactionItemView 작업
- 체크할 부분이 크게 없는 pr이라 3분 모두 리뷰어로 두었습니다. 빠르게 보시는 분이 승인해주시면 감사하겠습니더 ㅎㅎ
- 얼른 이 Pr을 머지해야 여러분도 메인 풀 받고 나서 작업할 때 제가 만든 뷰에서 에러가 안날거예요,,
closes #36 
> 💄 [Design] 폰트 수정 이전에 작업되었던 폰트 수정 및 적용

- EatPic-iOS/Sources/Components/ProfileImageView.swift
- 프로필 테두리 O 
- 프로필 테두리 X
- ProfileImageView 사용자 프로필을 원형 이미지 형태로 표시하기 위한 공용 컴포넌트 개발
- 이미지가 없을 경우 기본 placeholder(person.fill) 이미지로 대체
- 선택적으로 테두리 색상 및 두께를 설정 가능
- 유지보수 용이성을 위해 뷰에서 쓰이는 상수값 별도 enum으로 분리하여 관리
- 하단 바텀 시트 공용 컴포넌트 개발 예정
closes #33
> ✨[Feat] ProfileImageView 공용 컴포넌트 제작

- EatPic-iOS/Sources/Components/BadgeView.swift
linewidth + 사이즈 조정
lockedbadge와 사이즈 맞추기 위해 + linewidth 도 조절 가능하도록 코드 수정
홈뷰의 메인 화면 마무리 
> ✨ [Design] BadgeView 디자인 수정

- EatPic-iOS/Sources/Utilites/Extensions/View+Extensions.swift
- EatPic-iOS/Sources/Utilites/ViewStyle/NavigationHeader/CustomNavigationBarModifier.swift
<table>
<tr>
<td>
</td>
<td><img width="300" height="700" alt="image" src="https://github.com/user-attachments/assets/db051550-a2b1-48f8-9e1b-324b1e23aa5a" /></td>
</tr>
</table>
- 기존 CustomNavigationBar를 역할별로 분리하여 다음 2개의 ViewModifier로 재구성
- CenterNavigationBarModifier: 가운데 타이틀 영역만 설정
- RightNavigationBarModifier: 오른쪽 버튼 영역만 설정
- 각 Modifier에 대해 View 확장 함수 제공
- customCenterNavigationBar(title:)
- customRightNavigationBar(right:)
- 기존 customNavigationBar(title:, right:)도 유지
close #60
> ✨[Feat] 커스텀 내비게이션바 Modifier 분리 및 View 확장 함수 제공

- EatPic-iOS/Sources/Components/Badge/BadgeProgressModalView.swift
- EatPic-iOS/Sources/Components/Modal/AlertModalView.swift
- EatPic-iOS/Sources/Components/Modal/CameraRecordModalView.swift
- EatPic-iOS/Sources/Components/Modal/CompletionModalView.swift
- EatPic-iOS/Sources/Components/Modal/DecisionModalView.swift
버튼 액션 클로저 처리 안한 부분 수정 + closeBtn으로 이름 수정
> ✨ [Feat]: ModalView 코드 수정

- EatPic-iOS/Sources/Utilites/ViewStyle/NavigationHeader/GlobalNavigationBarStyle.swift
- 기존 CustomNavigationBar의 배경색이 투명색이었음
- 피그마 디자인과 일치시키기 위해 색상 지정
close #92 
> 💄 [Design] Custom NavigationBar Background Color 지정

- EatPic-iOS/Sources/Screens/FollowListView.swift
FollowListView UI 구현
- segmentedView로 팔로잉/팔로우 목록 나누어 볼 수 있도록 분리
- 팔로잉 여부에 따른 버튼 변화
- 검색탭에서 키워드 검색 시, 유저 필터링
- ExploreMainView UI 구현
closes #84 
> ✨ Feat: FollowListView UI 구현

- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray010.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray020.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray030.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray040.colorset/Contents.json
- EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray050.colorset/Contents.json
> 💄[Design] Color Hex값 변경

- EatPic-iOS/Sources/Screens/Calender/CalenderCard/CalenderCardView.swift
> ✨ [Feat] HomeView에 토스트 기능 추가

- EatPic-iOS/Sources/Components/Modal/DecisionModalView.swift
파라미터 추가하여 오른쪽 버튼 색상 변경 가능하게
closes #124
> ♻️ [Refactor]: DecisionModalView 오른쪽 버튼 색상 변경 가능하게

- EatPic-iOS/Sources/Screens/Record/Views/PicCardRecordView.swift
> ✨ Feat: Record에서 Pic카드 기록시 년월일 시간 불러오도록 수정

- EatPic-iOS/Sources/Utilites/Config/Config.swift
- Project.swift
- ATS http 허용(https로 변경 전까지)
- Project.swift에 xccofing 변수 등록 및 infoPlist 반영
- Config.swift에 static 함수를 통한 BASE_URL 등록
- api 연결 및 
close #131 
> 🔧 [Chore] API 연결을 위한 baseURL 등록 및 info plist 설정

- EatPic-iOS/Sources/Common/Enum/PicCardItemType.swift
- EatPic-iOS/Sources/Components/Card/PicCardItemView.swift
- EatPic-iOS/Sources/Components/Card/PicCardView.swift
- EatPic-iOS/Sources/Components/Reaction/ReactionBarView.swift
- EatPic-iOS/Sources/Models/Community/CommunityModel.swift
- EatPic-iOS/Sources/Screens/Community/ViewModels/CommunityMainViewModel.swift
- EatPic-iOS/Sources/Screens/Community/Views/CommunityMainView.swift
- 북마크/댓글/리액션 속성들은 let -> var로 수정하여 동적으로 변경 가능하도록 수정
- mutating 함수를 이용하여, 수정이 필요할 때에는 struct의 값도 바꿀 수 있도록 함
- onItemAction에 카드 ID를 함께 전달하도록 수정
- CommunityMainViewModel에서 카드 ID별로 상태 업데이트 가능
- 실제 filteredCards 배열의 데이터가 업데이트됨
사용자 액션 → PicCardItemView → PicCardView → CommunityMainView → CommunityMainViewModel → 카드 상태 업데이트 → UI 자동 반영
closes #144 
> ✨ Feat: PicCardView-북마크/댓글/리액션 수 연동

- EatPic-iOS/Sources/Components/Calendar/ViewModel/CalendarScrollViewModel.swift
- EatPic-iOS/Sources/Core/Networks/DTO/Response/CardFeedResponse.swift
- EatPic-iOS/Sources/Models/Community/CommunityModel.swift
- EatPic-iOS/Sources/Screens/Explore/ExploreSelectedView.swift
- EatPic-iOS/Sources/Screens/Home/Views/Recommend/RecomPicCardView.swift
- Response 모델 수정
- datetime으로 날짜와 시간이 한번에 들어오는데, 이걸 날짜와 시간으로 따로 계산해서 저장하는 포맷팅 함수 구현
closes #173 
> ✏️ Fix: 피드조회 API datetime 반영 완료

- EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
- EatPic-iOS/Sources/Core/Networks/TargetType/Card/CardTargetType.swift
- EatPic-iOS/Sources/Screens/Community/ViewModels/OthersProfileViewModel.swift
- EatPic-iOS/Sources/Screens/Community/Views/OthersProfileView.swift
> 🐛[ Fix] 다른 사람 프로필 조회시 Card리스트 안나오는 버그 해결

- EatPic-iOS/Sources/Screens/Home/ViewModels/MyBadgeStatusViewModel.swift
- EatPic-iOS/Sources/Screens/Home/Views/BadgeAll/MyBadgeStatusAllView.swift
> ✨ Feat: BadgeStatusAllView 렌더링 수정 및 뱃지 현황 수정  및 모달 수정

- EatPic-iOS/Sources/Core/Networks/DTO/Response/ProfileDetailResult.swift
- EatPic-iOS/Sources/Core/Networks/TargetType/Card/CardTargetType.swift
- EatPic-iOS/Sources/Screens/Community/ViewModels/OthersProfileViewModel.swift
- EatPic-iOS/Sources/Screens/Community/Views/OthersProfileView.swift
- 프로필 조회시 API 구현
- 픽카드 개수/ 팔로워/ 팔로잉 수/ 아이디/ 닉네임/ 한줄소개(옵셔널) 뷰에 바인딩
> ✨ [Feat] 다른사람 프로필 조회시 팔로워/팔로잉/픽카드 개수 조회 API 구현

- EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
- EatPic-iOS/Sources/Screens/Explore/ExploreSelectedView.swift
- EatPic-iOS/Sources/Screens/Home/ViewModels/MyBadgeStatusViewModel.swift
- EatPic-iOS/Sources/Screens/MyPage/Views/MyPageMainView.swift
- EatPic-iOS/Sources/Screens/MyPage/Views/SavedPicCard/SavedPicCardView.swift
- EatPic-iOS/Sources/Screens/MyPage/Views/SavedPicCard/SavedPicCardViewModel.swift
https://github.com/user-attachments/assets/aabe6d9f-270b-4561-bb85-1886a2a0732f
> ✨ Feat: 잇친들의 Pic카드 불러오기 + 메인 홈뷰에 획득 개수 불러옴

- EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
- EatPic-iOS/Sources/Screens/Home/Views/Recommend/RecomPicSingleCardView.swift
- EatPic-iOS/Sources/Screens/MyPage/Views/AllPicCard/MyAllPicCardView.swift
- 파일이름과 뷰 이름 달라 리팩토링 
https://github.com/user-attachments/assets/bc9f43cc-88c1-4ff8-9acb-3932f96d6d6f
- RecomPicCardSingleView에 프로필/식당위치 이동이 적용되어있지 않아 수정
https://github.com/user-attachments/assets/63f3fcf2-9e1d-471a-aff7-0bde6e18ea38
- MyPage픽카드뷰들(MyAllPicCard/SinglePicCard) (위 영상은 MyAllPicCard만))에서도 개별 피드로 네비게이션
> ✨ Feat: RecomPicCardSingleView에서 프로필/식당위치 이동 적용 + MyPage픽카드뷰들에서도 개별 피드로 네비게이션

- EatPic-iOS/Sources/Screens/MyPage/Views/MyPageMainView.swift
MyPageMainView의 introduction 잘리지 않도록 수정
> 🎨 Design: MyPageMainView의 introduction 잘리지 않도록 수정
